name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_BUILD_RUSTFLAGS: -C target-feature=+crt-static


jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --verbose --target x86_64-unknown-linux-gnu

  release:
    name: Release ${{ matrix.platform.target }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            ending:
            command: build

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ending: .exe
            command: both

          - os: macOS-latest
            target: x86_64-apple-darwin
            ending:
            command: both

            # more release targets here ...

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
      
      - name: Make executable
        run: chmod +x "target/${{ matrix.platform.target }}/release/${{ github.event.repository.name }}${{ matrix.platform.ending }}"
      
      - name: Publish release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.platform.target }}
          path: "target/${{ matrix.platform.target }}/release/${{ github.event.repository.name }}${{ matrix.platform.ending }}"